spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Learn?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1552827902

server:
  port: 8081

mybatis:
  mapper-locations: classpath:com/example/Mapper/*.xml
  type-aliases-package: com.example.demo.bean




#声明注入值
id: 3